postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite3: &sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *sqlite3
  database: db/development.sqlite3

  test:
    <<: *sqlite3
    database: db/test.sqlite3

production:
  <<: *postgresql
  database: bs5_demo_production
  username: bs5_demo
  password: <%= ENV['BS5_DEMO_DATABASE_PASSWORD'] %>
